/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.*;
import static java.lang.System.in;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author 7oda
 */
public class delete_doctor extends javax.swing.JFrame {

    String s;

    public delete_doctor() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        // panel2.setBackground(new Color(100, 255, 255, 150)); // to Opacity Jpanel 2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        view = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        adding = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logout3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        department = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        leave = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        blood = new javax.swing.JComboBox<>();
        phone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        join = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        view_data = new javax.swing.JButton();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Patient");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1230, 700));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(109, 73, 243));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setLayout(null);

        view.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View Doctor");
        view.setBorderPainted(false);
        view.setContentAreaFilled(false);
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        kGradientPanel1.add(view);
        view.setBounds(860, 0, 170, 70);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        logout.setToolTipText("Exit Program");
        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout);
        logout.setBounds(1190, 10, 40, 30);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hou.png"))); // NOI18N
        home.setToolTipText("Back to Home");
        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(home);
        home.setBounds(1060, 10, 40, 30);

        adding.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        adding.setForeground(new java.awt.Color(255, 255, 255));
        adding.setText("ADD Doctor");
        adding.setBorderPainted(false);
        adding.setContentAreaFilled(false);
        adding.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addingMouseEntered(evt);
            }
        });
        adding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addingActionPerformed(evt);
            }
        });
        kGradientPanel1.add(adding);
        adding.setBounds(340, 0, 170, 70);

        delete.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete Doctor");
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delete);
        delete.setBounds(510, 0, 170, 70);

        update.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update Doctor");
        update.setBorderPainted(false);
        update.setContentAreaFilled(false);
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(update);
        update.setBounds(690, 0, 190, 70);

        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("________________________________________________________________________________________\n");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(370, 50, 1020, 20);

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(photo);
        photo.setBounds(930, 160, 290, 260);

        pic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pic.setForeground(new java.awt.Color(255, 255, 102));
        pic.setText("  pic 2x2");
        kGradientPanel1.add(pic);
        pic.setBounds(930, 160, 70, 30);

        txt.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("  Delete Doctor");
        kGradientPanel1.add(txt);
        txt.setBounds(0, 0, 290, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DOCTORDETAILS (2).png"))); // NOI18N
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 150, 170);

        logout3.setBackground(new java.awt.Color(255, 255, 255));
        logout3.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        logout3.setToolTipText("Minimize");
        logout3.setBorder(null);
        logout3.setContentAreaFilled(false);
        logout3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout3MouseExited(evt);
            }
        });
        logout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout3);
        logout3.setBounds(1151, 11, 30, 30);

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Username");
        kGradientPanel1.add(jLabel21);
        jLabel21.setBounds(920, 490, 100, 30);

        username.setEditable(false);
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kGradientPanel1.add(username);
        username.setBounds(1030, 490, 160, 40);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        kGradientPanel1.add(jLabel17);
        jLabel17.setBounds(920, 580, 100, 30);

        password.setEditable(false);
        password.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        kGradientPanel1.add(password);
        password.setBounds(1030, 580, 160, 40);

        jPanel2.setBackground(new java.awt.Color(109, 73, 243));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Doctor ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 140, 40);

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(id);
        id.setBounds(170, 20, 110, 40);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(360, 110, 110, 40);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Second Name");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(360, 170, 130, 40);

        lname.setEditable(false);
        lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lname);
        lname.setBounds(500, 170, 210, 40);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Blood Group");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(360, 230, 120, 40);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Days");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 390, 70, 40);

        fname.setEditable(false);
        fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(fname);
        fname.setBounds(130, 110, 160, 34);

        days.setEditable(false);
        days.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(days);
        days.setBounds(500, 390, 210, 34);

        department.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Dentist", "CARDIOLOGY", "Accident and Emergency", "Neurology", "General Surgey", "Pharmacy", "Orthopaedics" }));
        jPanel2.add(department);
        department.setBounds(500, 110, 210, 40);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 170, 50, 40);

        age.setEditable(false);
        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(age);
        age.setBounds(130, 170, 160, 34);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 290, 60, 40);

        email.setEditable(false);
        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(email);
        email.setBounds(130, 290, 160, 34);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 230, 80, 40);

        leave.setEditable(false);
        leave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(leave);
        leave.setBounds(500, 440, 210, 34);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(360, 340, 80, 40);

        gender.setEditable(false);
        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(gender);
        gender.setBounds(130, 230, 160, 34);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Phone No");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(360, 290, 90, 40);

        blood.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+", "A-", "B+", "B-", "O+", "O-" }));
        jPanel2.add(blood);
        blood.setBounds(500, 230, 210, 40);

        phone.setEditable(false);
        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(phone);
        phone.setBounds(500, 290, 210, 34);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("First Name");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 110, 110, 40);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ctiy");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 350, 40, 40);

        city.setEditable(false);
        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(city);
        city.setBounds(130, 350, 160, 34);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Joining Date");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 420, 110, 40);

        join.setEditable(false);
        join.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(join);
        join.setBounds(130, 420, 160, 34);

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Leaving Date");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(360, 440, 120, 40);

        address.setEditable(false);
        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(address);
        address.setBounds(500, 340, 210, 34);

        view_data.setBackground(new java.awt.Color(255, 255, 255));
        view_data.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        view_data.setText("View Doctor");
        view_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_dataMouseExited(evt);
            }
        });
        view_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_dataActionPerformed(evt);
            }
        });
        jPanel2.add(view_data);
        view_data.setBounds(500, 20, 190, 50);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(190, 90, 720, 500);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/removeuser.png"))); // NOI18N
        add.setText("Delete Doctor");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        kGradientPanel1.add(add);
        add.setBounds(930, 90, 183, 60);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.setToolTipText("Clear all fields");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        kGradientPanel1.add(clear);
        clear.setBounds(1120, 90, 100, 60);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1240, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:


    }//GEN-LAST:event_logoutMouseExited

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setBackground(Color.YELLOW);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setBackground(Color.WHITE);
    }//GEN-LAST:event_homeMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.hide();
        new admin_control().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        // TODO add your handling code here:
        view.setForeground(Color.YELLOW);
        delete.setForeground(Color.WHITE);
        update.setForeground(Color.WHITE);
        adding.setForeground(Color.WHITE);

    }//GEN-LAST:event_viewMouseEntered

    private void addingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addingMouseEntered
        // TODO add your handling code here:
        adding.setForeground(Color.YELLOW);
        delete.setForeground(Color.WHITE);
        update.setForeground(Color.WHITE);
        view.setForeground(Color.WHITE);

    }//GEN-LAST:event_addingMouseEntered

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        delete.setForeground(Color.YELLOW);
        adding.setForeground(Color.WHITE);
        update.setForeground(Color.WHITE);
        view.setForeground(Color.WHITE);

    }//GEN-LAST:event_deleteMouseEntered

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        update.setForeground(Color.YELLOW);
        adding.setForeground(Color.WHITE);
        delete.setForeground(Color.WHITE);
        view.setForeground(Color.WHITE);

    }//GEN-LAST:event_updateMouseEntered

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        this.hide();
        new view_doctor().setVisible(true);

    }//GEN-LAST:event_viewActionPerformed


    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        this.hide();
        new update_doctor().setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    private void logout3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MouseEntered

    private void logout3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MouseExited

    private void logout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout3ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_logout3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

    }//GEN-LAST:event_deleteActionPerformed

    private void view_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_dataMouseEntered

        view_data.setBackground(new Color(109, 73, 243));
        view_data.setForeground(Color.WHITE);

    }//GEN-LAST:event_view_dataMouseEntered

    private void view_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_dataMouseExited
        // TODO add your handling code here:
        view_data.setBackground(Color.WHITE);
        view_data.setForeground(Color.BLACK);

    }//GEN-LAST:event_view_dataMouseExited

    private void view_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_dataActionPerformed

        String getID = id.getText();

        if (getID.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();   // alert
            JOptionPane.showMessageDialog(this, "Please Insert your ID !!", "Failure", JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
                String sqlStmt = "SELECT `department`, `fname`, `lname`, `age`, `blood`, `gender`, `phone`, `email`, `address`, `city`, `days`, `joinDate`, `leaveDate`, `username`, `password`,`image` FROM `doctor` WHERE id ='" + getID + "'";
                PreparedStatement stmt = con.prepareStatement(sqlStmt);

                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {

                    JOptionPane.showMessageDialog(this, "Your Id : " + getID + " is found Poress Ok to show data");
                    department.setSelectedItem(rs.getString("department"));
                    fname.setText(rs.getString("fname"));
                    lname.setText(rs.getString("lname"));
                    age.setText(rs.getString("age"));
                    blood.setSelectedItem(rs.getString("blood"));
                    gender.setText(rs.getString("gender"));
                    phone.setText(rs.getString("phone"));
                    email.setText(rs.getString("email"));
                    address.setText(rs.getString("address"));
                    city.setText(rs.getString("city"));
                    days.setText(rs.getString("days"));
                    join.setText(rs.getString("joinDate"));
                    leave.setText(rs.getString("leaveDate"));
                    username.setText(rs.getString("username"));
                    password.setText(rs.getString("password"));
                    BufferedImage im = ImageIO.read(rs.getBinaryStream("image")); // to to retrieve image from database  in jlabel
                    photo.setIcon(new ImageIcon(im));
                } else {
                    Toolkit.getDefaultToolkit().beep();   // alert
                    JOptionPane.showMessageDialog(this, "Your Id : " + getID + "  isn't  found !", "Failure", JOptionPane.ERROR_MESSAGE);
                    department.setSelectedItem("Select Department");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_view_dataActionPerformed

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        add.setBackground(new Color(109, 73, 243));
        add.setForeground(Color.WHITE);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setBackground(Color.WHITE);
        add.setForeground(Color.BLACK);
    }//GEN-LAST:event_addMouseExited

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String getID = id.getText();

        if (getID.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();   // alert

            JOptionPane.showMessageDialog(this, "Please Insert your ID !!", "Failure", JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
                String sqlStmt = "DELETE FROM `doctor` WHERE id = '" + getID + "'";
                PreparedStatement stmt = con.prepareStatement(sqlStmt);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your ID = " + getID + "  is deleted sucessfully :)");
                resetData();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_addActionPerformed

    private void addingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addingActionPerformed
        this.hide();
        new doctor_detail().setVisible(true);
    }//GEN-LAST:event_addingActionPerformed

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        clear.setBackground(new Color(109, 73, 243));
        clear.setForeground(Color.WHITE);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        clear.setBackground(Color.WHITE);
        clear.setForeground(Color.BLACK);
    }//GEN-LAST:event_clearMouseExited

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        resetData();
    }//GEN-LAST:event_clearActionPerformed
    public void resetData() {
        fname.setText("");
        id.setText("");
        lname.setText("");
        age.setText("");
        blood.setSelectedItem("Select");
        department.setSelectedItem("Select Department");
        gender.setText("");
        phone.setText("");
        email.setText("");
        address.setText("");
        city.setText("");
        days.setText("");
        join.setText("");
        leave.setText("");
        username.setText("");
        photo.setIcon(new ImageIcon());
        password.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton adding;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> blood;
    private javax.swing.JTextField city;
    private javax.swing.JButton clear;
    private javax.swing.JTextField days;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gender;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField join;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField leave;
    private javax.swing.JTextField lname;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout3;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel txt;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    private javax.swing.JButton view;
    private javax.swing.JButton view_data;
    // End of variables declaration//GEN-END:variables
}
