/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.*;
import static java.lang.System.in;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author 7oda
 */
public class department extends javax.swing.JFrame {

    public department() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        panel.setBackground(new Color(81, 28, 81, 40)); // to Opacity Jpanel 2
        table.setShowGrid(true);
        table.getTableHeader().setReorderingAllowed(false);
        search_id.hide();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logout3 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        txt = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        search_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dep_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dep_dis = new javax.swing.JTextField();
        display_data = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        department_name = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD Patient");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1230, 700));
        getContentPane().setLayout(null);

        kGradientPanel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(81, 28, 81));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setLayout(null);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        logout.setToolTipText("Exit Program");
        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout);
        logout.setBounds(1190, 10, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/department.png"))); // NOI18N
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 150, 160);

        logout3.setBackground(new java.awt.Color(255, 255, 255));
        logout3.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        logout3.setToolTipText("Minimize");
        logout3.setBorder(null);
        logout3.setContentAreaFilled(false);
        logout3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout3MouseExited(evt);
            }
        });
        logout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout3);
        logout3.setBounds(1151, 11, 30, 30);

        panel.setBackground(new java.awt.Color(81, 28, 81));
        panel.setLayout(null);

        txt.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("DEPARTMENT SECTION");
        panel.add(txt);
        txt.setBounds(20, 0, 480, 60);

        kGradientPanel1.add(panel);
        panel.setBounds(220, 20, 830, 70);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hou.png"))); // NOI18N
        home.setToolTipText("Back to Home");
        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(home);
        home.setBounds(1070, 40, 40, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ser.gif"))); // NOI18N
        jLabel3.setToolTipText("Search in Doctor");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(110, 530, 50, 40);

        search_id.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        search_id.setToolTipText("Search in Employee");
        search_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_idActionPerformed(evt);
            }
        });
        search_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_idKeyReleased(evt);
            }
        });
        kGradientPanel1.add(search_id);
        search_id.setBounds(250, 530, 250, 40);

        jScrollPane1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        table.setBackground(new java.awt.Color(211, 183, 227));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DEP_NO", "DEP_Name", "DEP_Discription"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(25);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 1220, 170);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Department Name");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(30, 370, 160, 24);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Department Discription");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(30, 460, 210, 24);

        dep_no.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        dep_no.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel1.add(dep_no);
        dep_no.setBounds(780, 360, 340, 40);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Department Number");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(580, 370, 190, 24);

        dep_dis.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        dep_dis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel1.add(dep_dis);
        dep_dis.setBounds(250, 450, 870, 40);

        display_data.setBackground(new java.awt.Color(255, 255, 255));
        display_data.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        display_data.setText("Display Table");
        display_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        display_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                display_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                display_dataMouseExited(evt);
            }
        });
        display_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_dataActionPerformed(evt);
            }
        });
        kGradientPanel1.add(display_data);
        display_data.setBounds(110, 610, 210, 50);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setText("ADD Department");
        add.setToolTipText("");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        kGradientPanel1.add(add);
        add.setBounds(380, 610, 210, 50);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        delete.setText("Delete Department");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delete);
        delete.setBounds(650, 610, 210, 50);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update.setText("Update Department");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(update);
        update.setBounds(910, 610, 210, 50);

        department_name.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        department_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Dentist", "CARDIOLOGY", "Accident and Emergency", "Neurology", "General Surgey", "Pharmacy", "Orthopaedics" }));
        kGradientPanel1.add(department_name);
        department_name.setBounds(250, 360, 280, 50);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1240, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.hide();
        new admin_control().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setBackground(Color.WHITE);
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setBackground(Color.ORANGE);
    }//GEN-LAST:event_homeMouseEntered

    private void logout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout3ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_logout3ActionPerformed

    private void logout3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MouseExited

    private void logout3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MouseEntered

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        search_id.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        search_id.hide();
        search_id.setText("");
    }//GEN-LAST:event_jLabel3MouseReleased

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_idActionPerformed

    private void search_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_idKeyReleased
        DefaultTableModel dm = (DefaultTableModel) table.getModel();
        String search = search_id.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_search_idKeyReleased

    private void display_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_dataMouseEntered
        // TODO add your handling code here:
        display_data.setBackground(new Color(81, 28, 81));
        display_data.setForeground(Color.WHITE);

    }//GEN-LAST:event_display_dataMouseEntered

    private void display_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_dataMouseExited
        // TODO add your handling code here:
        display_data.setBackground(Color.WHITE);
        display_data.setForeground(Color.BLACK);

    }//GEN-LAST:event_display_dataMouseExited

    private void display_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_dataActionPerformed
        // TODO add your handling code here:

        try {

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
            String sqlStmt = "SELECT `DEP_NO`, `DEP_Name`, `DEP_Discription` FROM `department`";
            PreparedStatement stmt = con.prepareStatement(sqlStmt);
            ResultSet rs = stmt.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs)); // to show data from db to jtable by (rs2xml) jar
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_display_dataActionPerformed

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(81, 28, 81));
        add.setForeground(Color.WHITE);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(Color.WHITE);
        add.setForeground(Color.BLACK);
    }//GEN-LAST:event_addMouseExited

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String getDepNo = dep_no.getText();
        String getDepDiscription = dep_dis.getText();
        String getDepName = department_name.getSelectedItem().toString();

        if (getDepNo.isEmpty() || getDepDiscription.isEmpty() || getDepName.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();   // alert
            JOptionPane.showMessageDialog(this, "please Fill out Fileds   !!", "Failure", JOptionPane.ERROR_MESSAGE);

        } else {
            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
                String sqlStmt = "INSERT INTO `department`(`DEP_NO`, `DEP_Name`, `DEP_Discription`) VALUES (?,?,?)";
                PreparedStatement stmt = con.prepareStatement(sqlStmt);
                stmt.setString(1, getDepNo);
                stmt.setString(2, getDepName);
                stmt.setString(3, getDepDiscription);
                stmt.execute();
                JOptionPane.showMessageDialog(this, "Your Record is added sucessfully :)");
                resetData();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        delete.setBackground(new Color(81, 28, 81));
        delete.setForeground(Color.WHITE);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setBackground(Color.WHITE);
        delete.setForeground(Color.BLACK);
    }//GEN-LAST:event_deleteMouseExited

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String getDep_No = dep_no.getText();

        if (getDep_No.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();   // alert
            JOptionPane.showMessageDialog(this, "Please Insert your ID !!", "Failure", JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
                String sqlStmt = "DELETE FROM `department` WHERE DEP_NO = '" + getDep_No + "'";
                PreparedStatement stmt = con.prepareStatement(sqlStmt);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your Dep_No = " + getDep_No + "  is deleted sucessfully :)");
                resetData();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        update.setBackground(new Color(81, 28, 81));
        update.setForeground(Color.WHITE);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        update.setBackground(Color.WHITE);
        update.setForeground(Color.BLACK);
    }//GEN-LAST:event_updateMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String getDepNo = dep_no.getText();
        String getDepDiscription = dep_dis.getText();
        String getDepName = department_name.getSelectedItem().toString();

        if (getDepNo.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();   // alert

            JOptionPane.showMessageDialog(this, "Please Insert your ID !!", "Failure", JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
                String sqlStmt = "UPDATE `department` SET `DEP_Name`='" + getDepName + "',`DEP_Discription`='" + getDepDiscription + "' WHERE DEP_NO = '" + getDepNo + "'";
                PreparedStatement stmt = con.prepareStatement(sqlStmt);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your Record = " + getDepNo + "  is Updated sucessfully :)");
                resetData();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        showData();
    }//GEN-LAST:event_tableMouseClicked

    private void resetData() {
        dep_no.setText("");
        dep_dis.setText("");
        department_name.setSelectedItem("Select Department");

    }

    private void showData() {

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selected = table.getSelectedRow();
        if (selected >= 0) {
            dep_no.setText(model.getValueAt(selected, 0).toString());
            department_name.setSelectedItem((model.getValueAt(selected, 1).toString()));
            dep_dis.setText(model.getValueAt(selected, 2).toString());

        } else {
            Toolkit.getDefaultToolkit().beep();   // alert
            JOptionPane.showMessageDialog(this, "Please Select row from Table to Display data !!", "Failure", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dep_dis;
    private javax.swing.JTextField dep_no;
    private javax.swing.JComboBox<String> department_name;
    private javax.swing.JButton display_data;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout3;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField search_id;
    private javax.swing.JTable table;
    private javax.swing.JLabel txt;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
