/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.*;
import static java.lang.System.in;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 7oda
 */
public class doctor_detail extends javax.swing.JFrame {

    String s = "null";

    public doctor_detail() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        // panel2.setBackground(new Color(100, 255, 255, 150)); // to Opacity Jpanel 2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        view = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        adding = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        getPath = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logout3 = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        department = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        leave = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        blood = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        join = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        show = new javax.swing.JToggleButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD Patient");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1230, 700));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(109, 73, 243));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setLayout(null);

        view.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View Doctor");
        view.setBorderPainted(false);
        view.setContentAreaFilled(false);
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        kGradientPanel1.add(view);
        view.setBounds(860, 0, 170, 70);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        logout.setToolTipText("Exit Program");
        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout);
        logout.setBounds(1190, 10, 40, 30);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hou.png"))); // NOI18N
        home.setToolTipText("Back to Home");
        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(home);
        home.setBounds(1060, 10, 40, 30);

        adding.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        adding.setForeground(new java.awt.Color(255, 255, 255));
        adding.setText("ADD Doctor");
        adding.setBorderPainted(false);
        adding.setContentAreaFilled(false);
        adding.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addingMouseEntered(evt);
            }
        });
        kGradientPanel1.add(adding);
        adding.setBounds(340, 0, 170, 70);

        delete.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete Doctor");
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delete);
        delete.setBounds(510, 0, 170, 70);

        update.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update Doctor");
        update.setBorderPainted(false);
        update.setContentAreaFilled(false);
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(update);
        update.setBounds(690, 0, 190, 70);

        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("________________________________________________________________________________________\n");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(370, 50, 1020, 20);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (5).png"))); // NOI18N
        add.setText("ADD Doctor");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        kGradientPanel1.add(add);
        add.setBounds(930, 90, 170, 60);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.setToolTipText("Clear all fields");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        kGradientPanel1.add(clear);
        clear.setBounds(1120, 90, 100, 60);

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(photo);
        photo.setBounds(930, 160, 290, 260);

        pic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pic.setForeground(new java.awt.Color(255, 255, 102));
        pic.setText("  pic 2x2");
        kGradientPanel1.add(pic);
        pic.setBounds(930, 160, 70, 30);

        getPath.setEditable(false);
        getPath.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getPath.setForeground(new java.awt.Color(255, 255, 255));
        getPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getPath.setOpaque(false);
        kGradientPanel1.add(getPath);
        getPath.setBounds(930, 450, 290, 40);

        browse.setBackground(new java.awt.Color(255, 255, 255));
        browse.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        browse.setText("Browse");
        browse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                browseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                browseMouseExited(evt);
            }
        });
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        kGradientPanel1.add(browse);
        browse.setBounds(1030, 510, 140, 50);

        txt.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("  ADD Doctor");
        kGradientPanel1.add(txt);
        txt.setBounds(0, 0, 290, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DOCTORDETAILS (2).png"))); // NOI18N
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 150, 160);

        logout3.setBackground(new java.awt.Color(255, 255, 255));
        logout3.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        logout3.setToolTipText("Minimize");
        logout3.setBorder(null);
        logout3.setContentAreaFilled(false);
        logout3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout3MouseExited(evt);
            }
        });
        logout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout3);
        logout3.setBounds(1151, 11, 30, 30);

        panel2.setBackground(new java.awt.Color(109, 73, 243));
        panel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Doctor ID");
        panel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 140, 40);

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(id);
        id.setBounds(170, 20, 110, 40);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department");
        panel2.add(jLabel5);
        jLabel5.setBounds(380, 20, 110, 40);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Second Name");
        panel2.add(jLabel6);
        jLabel6.setBounds(370, 110, 130, 40);

        lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(lname);
        lname.setBounds(500, 110, 210, 40);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Blood Group");
        panel2.add(jLabel7);
        jLabel7.setBounds(370, 170, 120, 40);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Days");
        panel2.add(jLabel8);
        jLabel8.setBounds(370, 350, 70, 40);

        fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(fname);
        fname.setBounds(130, 110, 160, 34);

        days.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(days);
        days.setBounds(500, 350, 210, 34);

        department.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Dentist", "CARDIOLOGY", "Accident and Emergency", "Neurology", "General Surgey", "Pharmacy", "Orthopaedics" }));
        panel2.add(department);
        department.setBounds(500, 20, 210, 40);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age");
        panel2.add(jLabel10);
        jLabel10.setBounds(20, 170, 50, 40);

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(age);
        age.setBounds(130, 170, 160, 34);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        panel2.add(jLabel11);
        jLabel11.setBounds(20, 290, 60, 40);

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(email);
        email.setBounds(130, 290, 160, 34);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        panel2.add(jLabel12);
        jLabel12.setBounds(20, 230, 80, 40);

        leave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(leave);
        leave.setBounds(500, 410, 210, 34);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address");
        panel2.add(jLabel13);
        jLabel13.setBounds(370, 290, 80, 40);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Phone No");
        panel2.add(jLabel14);
        jLabel14.setBounds(370, 230, 90, 40);

        blood.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+", "A-", "B+", "B-", "O+", "O-" }));
        panel2.add(blood);
        blood.setBounds(500, 180, 210, 40);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("First Name");
        panel2.add(jLabel15);
        jLabel15.setBounds(20, 110, 110, 40);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ctiy");
        panel2.add(jLabel16);
        jLabel16.setBounds(20, 350, 40, 40);

        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(city);
        city.setBounds(130, 350, 160, 34);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Joining Date");
        panel2.add(jLabel18);
        jLabel18.setBounds(10, 420, 110, 40);

        join.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(join);
        join.setBounds(130, 420, 160, 34);

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Leaving Date");
        panel2.add(jLabel19);
        jLabel19.setBounds(360, 410, 120, 40);

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(address);
        address.setBounds(500, 290, 210, 34);

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel2.add(phone);
        phone.setBounds(500, 240, 210, 34);

        gender.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "male", "female" }));
        panel2.add(gender);
        gender.setBounds(130, 230, 160, 40);

        kGradientPanel1.add(panel2);
        panel2.setBounds(190, 90, 720, 510);

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Username");
        kGradientPanel1.add(jLabel21);
        jLabel21.setBounds(920, 590, 100, 30);

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kGradientPanel1.add(username);
        username.setBounds(1020, 590, 160, 40);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        kGradientPanel1.add(jLabel17);
        jLabel17.setBounds(920, 650, 100, 30);

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.gif"))); // NOI18N
        show.setToolTipText("show password");
        show.setBorder(null);
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.setOpaque(true);
        show.setPreferredSize(new java.awt.Dimension(52, 30));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        kGradientPanel1.add(show);
        show.setBounds(1140, 660, 30, 20);

        password.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        kGradientPanel1.add(password);
        password.setBounds(1020, 650, 160, 40);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1240, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:


    }//GEN-LAST:event_logoutMouseExited

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setBackground(Color.YELLOW);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setBackground(Color.WHITE);
    }//GEN-LAST:event_homeMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.hide();
        new admin_control().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        // TODO add your handling code here:
        view.setForeground(Color.YELLOW);
        delete.setForeground(Color.WHITE);
        update.setForeground(Color.WHITE);
        adding.setForeground(Color.WHITE);

    }//GEN-LAST:event_viewMouseEntered

    private void addingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addingMouseEntered
        // TODO add your handling code here:
        adding.setForeground(Color.YELLOW);
        delete.setForeground(Color.WHITE);
        update.setForeground(Color.WHITE);
        view.setForeground(Color.WHITE);

    }//GEN-LAST:event_addingMouseEntered

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        delete.setForeground(Color.YELLOW);
        adding.setForeground(Color.WHITE);
        update.setForeground(Color.WHITE);
        view.setForeground(Color.WHITE);

    }//GEN-LAST:event_deleteMouseEntered

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        update.setForeground(Color.YELLOW);
        adding.setForeground(Color.WHITE);
        delete.setForeground(Color.WHITE);
        view.setForeground(Color.WHITE);

    }//GEN-LAST:event_updateMouseEntered

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

        this.hide();
        new view_doctor().setVisible(true);
    }//GEN-LAST:event_viewActionPerformed


    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(109,73,243));
        add.setForeground(Color.WHITE);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(Color.WHITE);
        add.setForeground(Color.BLACK);


    }//GEN-LAST:event_addMouseExited

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String getID = id.getText();
        String getDep = department.getSelectedItem().toString();
        String getFname = fname.getText();
        String getLname = lname.getText();
        String getAge = age.getText();
        String getBlood = blood.getSelectedItem().toString();
        String getGender = gender.getSelectedItem().toString();
        String getPhone = phone.getText();
        String getEmail = email.getText();
        String getAddress = address.getText();
        String getCity = city.getText();
        String getDays = days.getText();
        String getjoin = join.getText();
        String getLeave = leave.getText();
        String getUsername = username.getText();
        String getPassword = password.getText();

        if (getID.isEmpty() || getDep.isEmpty() || getFname.isEmpty() || getLname.isEmpty() || getAge.isEmpty() || getBlood.isEmpty() || getBlood.isEmpty() || getGender.isEmpty() || getPhone.isEmpty() || getEmail.isEmpty() || getAddress.isEmpty() || getCity.isEmpty() || getDays.isEmpty() || getjoin.isEmpty() || getLeave.isEmpty() || getUsername.isEmpty() || getPassword.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();   // alert
            JOptionPane.showMessageDialog(this, "please Fill all Fileds   !!", "Failure", JOptionPane.ERROR_MESSAGE);

        }
        if (s == "null") {
            Toolkit.getDefaultToolkit().beep();   // alert
            JOptionPane.showMessageDialog(this, "Plaes insert New photo   !!", "Failure", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
                String sqlStmt = "INSERT INTO `doctor`(`id`, `department`, `fname`, `lname`, `age`, `blood`, `gender`, `phone`, `email`, `address`, `city`, `days`, `joinDate`, `leaveDate`, `username`, `password`,image) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement stmt = con.prepareStatement(sqlStmt);
                InputStream Is = new FileInputStream(new File(s));
                stmt.setString(1, getID);
                stmt.setString(2, getDep);
                stmt.setString(3, getFname);
                stmt.setString(4, getLname);
                stmt.setString(5, getAge);
                stmt.setString(6, getBlood);
                stmt.setString(7, getGender);
                stmt.setString(8, getPhone);
                stmt.setString(9, getEmail);
                stmt.setString(10, getAddress);
                stmt.setString(11, getCity);
                stmt.setString(12, getDays);
                stmt.setString(13, getjoin);
                stmt.setString(14, getLeave);
                stmt.setString(15, getUsername);
                stmt.setString(16, getPassword);
                stmt.setBlob(17, Is);
                stmt.execute();
                JOptionPane.showMessageDialog(this, "Your Record is added sucessfully :)");
                resetData();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            } catch (FileNotFoundException ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_addActionPerformed

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        clear.setBackground(new Color(109,73,243));
        clear.setForeground(Color.WHITE);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        clear.setBackground(Color.WHITE);
        clear.setForeground(Color.BLACK);

    }//GEN-LAST:event_clearMouseExited

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        resetData();
    }//GEN-LAST:event_clearActionPerformed

    private void browseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseMouseEntered
        // TODO add your handling code here:
         browse.setBackground(new Color(109,73,243));
        browse.setForeground(Color.WHITE);

    }//GEN-LAST:event_browseMouseEntered

    private void browseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseMouseExited
        // TODO add your handling code here:
        browse.setBackground(Color.WHITE);
        browse.setForeground(Color.BLACK);

    }//GEN-LAST:event_browseMouseExited

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(this);
        File f = choose.getSelectedFile();

        photo.setIcon(new ImageIcon(f.toString()));
        String path = f.getAbsolutePath();
        s = path;
        getPath.setText(path);
        pic.setVisible(false);
    }//GEN-LAST:event_browseActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        this.hide();
        new update_doctor().setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    private void logout3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MouseEntered

    private void logout3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MouseExited

    private void logout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout3ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_logout3ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        char c = '•';

        if (show.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar(c);

        }
    }//GEN-LAST:event_showActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        this.hide();
        new delete_doctor().setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed
    public void resetData() {
        id.setText("");
        blood.setSelectedItem("Select");
        department.setSelectedItem("Select Department");
        gender.setSelectedItem("Select");
        fname.setText("");
        lname.setText("");
        age.setText("");
        phone.setText("");
        address.setText("");
        days.setText("");
        join.setText("");
        photo.setIcon(new ImageIcon());
        getPath.setText("");
        email.setText("");
        city.setText("");
        leave.setText("");

        pic.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor_detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton adding;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> blood;
    private javax.swing.JButton browse;
    private javax.swing.JTextField city;
    private javax.swing.JButton clear;
    private javax.swing.JTextField days;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField getPath;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField join;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField leave;
    private javax.swing.JTextField lname;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout3;
    private javax.swing.JPanel panel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel pic;
    private javax.swing.JToggleButton show;
    private javax.swing.JLabel txt;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
