/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 7oda
 */
public class HMS extends javax.swing.JFrame {

    /**
     * Creates new form HMS
     */
    public HMS() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        pharmacist.setToolTipText("Login With Admin");
        recep.setToolTipText("Login With Receptionist");
        doctor.setToolTipText("Login With Doctor");
        pharmacist.setToolTipText("Login With Pharmacist");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharmacist = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        doctor1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        recep = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1190, 650));
        getContentPane().setLayout(null);

        pharmacist.setBackground(new java.awt.Color(255, 255, 255));
        pharmacist.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        pharmacist.setForeground(new java.awt.Color(0, 153, 204));
        pharmacist.setText("PHARMACIST");
        pharmacist.setBorder(null);
        pharmacist.setBorderPainted(false);
        pharmacist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharmacist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pharmacistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pharmacistMouseExited(evt);
            }
        });
        pharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistActionPerformed(evt);
            }
        });
        getContentPane().add(pharmacist);
        pharmacist.setBounds(830, 450, 180, 60);

        jPanel1.setBackground(new java.awt.Color(0, 177, 227));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                      Hospital Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 1190, 100);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        logout.setToolTipText("Exit Program");
        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(1140, 0, 40, 30);

        logout1.setBackground(new java.awt.Color(255, 255, 255));
        logout1.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        logout1.setToolTipText("Minimize");
        logout1.setBorder(null);
        logout1.setContentAreaFilled(false);
        logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout1MouseExited(evt);
            }
        });
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        getContentPane().add(logout1);
        logout1.setBounds(1100, 0, 30, 30);

        doctor1.setBackground(new java.awt.Color(255, 255, 255));
        doctor1.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        doctor1.setForeground(new java.awt.Color(0, 153, 204));
        doctor1.setBorder(null);
        doctor1.setBorderPainted(false);
        doctor1.setContentAreaFilled(false);
        doctor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor1ActionPerformed(evt);
            }
        });
        getContentPane().add(doctor1);
        doctor1.setBounds(930, 490, 130, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText(" Login as");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(540, 150, 210, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pharmacy.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(850, 280, 130, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 290, 130, 140);

        admin.setBackground(new java.awt.Color(255, 255, 255));
        admin.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 153, 204));
        admin.setText("ADMIN");
        admin.setBorder(null);
        admin.setBorderPainted(false);
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin);
        admin.setBounds(190, 450, 170, 60);

        recep.setBackground(new java.awt.Color(255, 255, 255));
        recep.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        recep.setForeground(new java.awt.Color(0, 153, 204));
        recep.setText("RECEPTIONIST");
        recep.setBorder(null);
        recep.setBorderPainted(false);
        recep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recepMouseExited(evt);
            }
        });
        recep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepActionPerformed(evt);
            }
        });
        getContentPane().add(recep);
        recep.setBounds(390, 450, 210, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receptionist.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 280, 130, 140);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor (4).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(640, 280, 130, 140);

        doctor.setBackground(new java.awt.Color(255, 255, 255));
        doctor.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        doctor.setForeground(new java.awt.Color(0, 153, 204));
        doctor.setText("DOCTOR");
        doctor.setBorder(null);
        doctor.setBorderPainted(false);
        doctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctorMouseExited(evt);
            }
        });
        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });
        getContentPane().add(doctor);
        doctor.setBounds(640, 450, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hmbackground.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1220, 675));
        jLabel1.setMinimumSize(new java.awt.Dimension(1220, 675));
        jLabel1.setPreferredSize(new java.awt.Dimension(1230, 700));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1190, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistActionPerformed
        // TODO add your handling code here:
        this.hide();
        new medicine_detail().setVisible(true);
    }//GEN-LAST:event_pharmacistActionPerformed

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutMouseExited

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MouseEntered

    private void logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_logout1MouseExited

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_logout1ActionPerformed

    private void doctor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor1ActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        new admin_login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_adminActionPerformed

    private void recepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepActionPerformed
        new reception_login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_recepActionPerformed

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
        new doctor_login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_doctorActionPerformed

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        admin.setBackground(new Color(0, 153, 204));
        admin.setForeground(Color.WHITE);
    }//GEN-LAST:event_adminMouseEntered

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        admin.setBackground(Color.WHITE);
        admin.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_adminMouseExited

    private void recepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recepMouseEntered
        recep.setBackground(new Color(0, 153, 204));
        recep.setForeground(Color.WHITE);
    }//GEN-LAST:event_recepMouseEntered

    private void recepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recepMouseExited
        recep.setBackground(Color.WHITE);
        recep.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_recepMouseExited

    private void doctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseEntered
        doctor.setBackground(new Color(0, 153, 204));
        doctor.setForeground(Color.WHITE);
    }//GEN-LAST:event_doctorMouseEntered

    private void doctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseExited
        doctor.setBackground(Color.WHITE);
        doctor.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_doctorMouseExited

    private void pharmacistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacistMouseEntered
        pharmacist.setBackground(new Color(0, 153, 204));
        pharmacist.setForeground(Color.WHITE);

    }//GEN-LAST:event_pharmacistMouseEntered

    private void pharmacistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacistMouseExited
        pharmacist.setBackground(Color.WHITE);
        pharmacist.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_pharmacistMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton doctor;
    private javax.swing.JButton doctor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JButton pharmacist;
    private javax.swing.JButton recep;
    // End of variables declaration//GEN-END:variables
}
